- id: astyle-c
  name: astyle-c
  description: Run astyle for C files.
  language: system
  entry: astyle
  types: [c]
  additional_dependencies: [astyle]

- id: astyle-cpp
  name: astyle-c++
  description: Run astyle for C++ files.
  language: system
  entry: astyle
  types: [c++]
  additional_dependencies: [astyle]

- id: astyle-cs
  name: astyle-c#
  description: Run astyle for C# files.
  language: system
  entry: astyle
  types: [c#]
  additional_dependencies: [astyle]

- id: shfmt
  name: shfmt
  description: Run shfmt for shell scripts.
  language: system
  entry: shfmt
  args: [-l, -w, -i, '4', -ci, -sr]
  types: [shell]
  additional_dependencies: [shfmt]

- id: push-guard
  name: push-guard
  description: Block push to certain remote branches.
  language: script
  entry: git_hooks/push-guard.sh
  stages: [push]
  always_run: true
