- id: astyle-c
  name: astyle-c
  description: Run astyle for C files.
  language: system
  entry: astyle
  types: [c]

- id: astyle-cpp
  name: astyle-c++
  description: Run astyle for C++ files.
  language: system
  entry: astyle
  types: [c++]

- id: astyle-c-in
  name: astyle-c-in
  description: Run astyle for C/C++ .in files.
  language: system
  entry: astyle
  files: \.(h|c|hpp|cpp)\.in$

- id: astyle-cs
  name: astyle-c#
  description: Run astyle for C# files.
  language: system
  entry: astyle
  types: [c#]

- id: shfmt
  name: shfmt
  description: Run shfmt for shell scripts.
  language: system
  entry: shfmt
  args: [-l, -w, -i, '4', -ci, -sr]
  types: [shell]
