if [ -f ~/.bashrc ]; then
    source ~/.bashrc
fi


# pip --user
PATH=$PATH:$HOME/.local/bin


# .NET
PATH=$PATH:$HOME/.dotnet


## Ruby
#
# @reference    Ruby Gems FAQs
#               https://guides.rubygems.org/faqs/
##
if which ruby >/dev/null && which gem >/dev/null; then
    PATH="$(ruby -r rubygems -e 'puts Gem.user_dir')/bin:$PATH"
fi
