name: config-sh-master

on:  # yamllint disable-line rule:truthy
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ubuntu-setup-and-check:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Add Git stable releases repo
      run: sudo add-apt-repository ppa:git-core/ppa
      shell: bash

    - name: Setup
      run: ./main.sh
      shell: bash

    - name: Test
      run: ./tests/tests_runner.sh
      shell: bash

  # To test this locally:
  # $ docker run --rm -v .:/workspace -w /workspace redhat/ubi9 bash -c "./main.sh"
  redhat-setup-and-check:
    runs-on: ubuntu-latest

    container:
      image: redhat/ubi9

    steps:
    - name: Install Git
      run: dnf --assumeyes install git
      shell: bash

    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup
      run: ./main.sh
      shell: bash
